services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: service-php
    volumes:
      - php_socket:/var/run/php
    networks:
      - service-network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: service-nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - php_socket:/var/run/php
    networks:
      - service-network

networks:
  service-network:
    driver: bridge

volumes:
  php_socket:
